steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "gcr.io/$PROJECT_ID/<GCP_PROJECT_NAME>-back-$_ENVIRONMENT:$REVISION_ID", "."]
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/<GCP_PROJECT_NAME>-back-$_ENVIRONMENT:$REVISION_ID"]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', '<GCP_PROJECT_NAME>-back-$_ENVIRONMENT',
           '--image', 'gcr.io/$PROJECT_ID/<GCP_PROJECT_NAME>-back-$_ENVIRONMENT:$REVISION_ID',
           '--region', 'us-east1',
           '--platform', 'managed',
           '--memory', '512Mi',
           '--update-env-vars', 'NODE_ENV=$_ENVIRONMENT,NODE_PORT=8080',
           '--quiet',
           '--allow-unauthenticated']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'services', 'update-traffic', '<GCP_PROJECT_NAME>-back-$_ENVIRONMENT',
           '--region', 'us-east1',
           '--platform', 'managed',
           '--to-latest']
images: ['gcr.io/$PROJECT_ID/<GCP_PROJECT_NAME>-back-$_ENVIRONMENT:$REVISION_ID']

