version: '3.4'
services:
  back:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: devops/clean-code-api-boilerplate-dev:latest
    container_name: clean-code-api-boilerplate-dev
    restart: always
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: 'local'
    expose:
      - 3000
    volumes:
      - type: bind
        source: ./src
        target: /clean-code-api-boilerplate/src
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - app
    tty: true
  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    environment:
      - MONGO_INITDB_DATABASE=clean-code-api-local
      - MONGO_INITDB_ROOT_USERNAME=mongomaster
      - MONGO_INITDB_ROOT_PASSWORD=ImTheMongoMasterBendTheKnee
    volumes:
      - ./src/repositories/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongodb-volume:/data/db:rw
    ports:
      - '27017:27017'
    expose:
      - 27017
    networks:
      - app
networks:
  app:
    driver: bridge
volumes:
  mongodb-volume:
    driver: local

